# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d373e1b80d6716060dc73ae1814f6e098b6de7899ca2d15710acd3cd2bb139355ff413aaaffb0fcb637f2842b0f8d4b473fe971b25a1b414e80b51e375f1e28

test:
  secret_key_base: 0f8b0cf39e92e8d913a51349a37dc02b47e9f333b039a24a11d5a296a0fdbeb30fead9ed02ad8e64eb32ef94d768736d0a4647ae1a0d275a46a816463e20a77e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
